FROM node:14.8.0-alpine as builder

RUN mkdir /usr/src/app

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY ./ /usr/src/app/
COPY ./package-lock.json /usr/src/app/

RUN npm install
RUN npm install react-scripts@1.1.1 -g

COPY ./ /usr/src/app/

RUN npm run build


